#!/bin/bash

cd $2

poetry shell

for i in $(seq 1 $3); do
  cd ..
done

case "$1" in
    init)
      python ./lib/migrator/init.py ./lib/migrator $4 $5
        ;;
    make)
      python ./lib/migrator/make.py ./lib/migrator $4 $5 $6
            ;;
    execute)
      python ./lib/migrator/execute.py ./lib/migrator $4 $5
            ;;
    *)
        echo "Usage: $0 {init|make|execute} [-args]"
        exit 1

esac
