#!/bin/bash

cd $2


case "$1" in
    init)
      poetry run python ./lib/migrator/init.py $3/../lib/migrator $4 $5
        ;;
    make)
      poetry run python ./lib/migrator/make.py $3/../lib/migrator $4 $5 $6
            ;;
    execute)
      poetry run python ./lib/migrator/execute.py $3/../lib/migrator $4 $4
            ;;
    *)
        echo "Usage: $0 {init|make|execute} [-args]"
        exit 1

esac
